name: Validate Packer JSON files

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ansible-ipi-install

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install ansible and dependencies.
        run: pip install ansible yamllint ansible-lint

      - name: Lint with yamllint
        run: yamllint .

      - name: Lint with ansible-lint
        run: ansible-lint
        if: always()