name: Validate Packer JSON files

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install ansible and dependencies.
        run: pip install ansible yamllint ansible-lint

      - name: Lint with yamllint and ansible-lint
        run: |
          cd ansible-ipi-install
          yamllint .
          ansible-lint
